site_name: Google Docs

nav:
- Overview: index.md
- Create a document: fl/create.md
- Download: fl/download.md
- Print: fl/print.md
- Manage access: fl/access.md
- Manage page settings: fl/settings.md
- Format the text: fl/format.md
- Additional content: fl/content.md
- Add-ons: fl/add-ons.md
- Help center: fl/help.md

theme:
  name: material
  logo: img/logo.png
  palette: 
    primary: white
  feature:
    tabs: false
  language: 'en'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.extra
  - pymdownx.snippets:
      base_path: docs/fl

plugins:
  - search